### ISSUE TITLE
How would socketcluster work with in this setup

### ISSUE THREAD

**Issue by slidenerd** [lautiamkok/spectre#1]
First of all, thank you for your fantastic efforts in making this repo. If you had to add socketcluster to this setup on the server side, would it be possible for you to add a separate repo with express for that if it isnt too much to ask, regards

**Comment by lautiamkok** [comment]
@slidenerd  thanks. glad you enjoy this repo. socketcluster? do you mean this https://socketcluster.io/#!/?

what do you need socketcluster for?

**Comment by slidenerd** [comment]
Yes that is the socketcluster I am talking about, I am looking to run multiple node processes and have websocket functionality to send json data to connected clients, I was searching for something in their issues where I found your comment here https://github.com/SocketCluster/socketcluster-client/issues/89 then I stumbled upon your account and found all the nuxt repos :) hence was curious to know if you have quit using socketcluster or did you abandon it in favor of socketio while using nuxt

**Comment by lautiamkok** [comment]
@slidenerd yes, I prefer socketio as it is simpler. but I think they achieve the same thing actually no matter which you use. here is the repo i made with socketio https://github.com/lautiamkok/koa-realtime

I might give socketcluster another go at some point in the future.

**Comment by slidenerd** [comment]
Thanks for replying :) i saw the sample, seems it uses a single process, if it isnt too much to ask could you add a cluster module version of it

**Comment by lautiamkok** [comment]
@slidenerd do you mean adding 'a cluster' to  https://github.com/lautiamkok/koa-realtime?

What do you need 'a cluster' for? Can you give me more details? Please provide me a user story so I can understand your situation.

**Comment by slidenerd** [comment]
I am trying to get ws data from multiple data sources like bittrex bitfinex etc, There are 3 different endpoints I was trying to retrieve per data source like tickers candles orderbooks and wanted to do each endpoint in a process like process 1: tickers , process 2: candles  and so on, hence was asking about the cluster

**Comment by lautiamkok** [comment]
@slidenerd so why do you need Socket.io or a realtime technology in this process?

**Comment by slidenerd** [comment]
To send updates to the browser every second or so

**Comment by lautiamkok** [comment]
@slidenerd  sorry been busy. didn't have time to check messages here.

if the source where you get the data from is not a realtime API, there is no use to make you side a realtime app. isn't it?

**Comment by slidenerd** [comment]
@lautiamkok no worries, the source is real time data unfortunately like a websocket API

**Comment by lautiamkok** [comment]
@slidenerd  can i have the source address so i can play around with the data?

**Comment by slidenerd** [comment]
I havent coded anything yet, I merely wanted to check with you if you are aware of how to cluster socket io /socketcluster to send receive live stream of data from/to the browser

**Comment by lautiamkok** [comment]
@slidenerd i haven't got time to explore the cluster possibility with socket io yet. but i think it is possible.

**Comment by lautiamkok** [comment]
@slidenerd i think these might be what you are looking for?

https://socket.io/docs/using-multiple-nodes/
https://stackoverflow.com/questions/18310635/scaling-socket-io-to-multiple-node-js-processes-using-cluster

**Comment by slidenerd** [comment]
Seen both , thanks for the help man

**Comment by lautiamkok** [comment]
@slidenerd and more

http://maxprog.net.pl/node-js/socket-io-on-node-js-cluster-a-simply-way-to-performance/
https://www.npmjs.com/package/socket.io-cluster

I can't develop anything for the cluster now unless i have a clear user story.
